### ISSUE TITLE
Could I remove this from Jenkins

### ISSUE THREAD

**Issue by marco-brandizi** [jenkinsci/icon-shim-plugin#9]
Jenkins tells me this plug-in is deprecated, but I don't get if I could safely remove it (from Jenkins 2.263.4). Will everything work fine after removal? Would I need to do something (before or after the removal) to ensure everything will work fine?

**Comment by MarkEWaite** [comment]
The issue tracker site is used to track issues.  Your request seems to be a request for help, not a report of an issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.

In the case of your specific question, yes, you can remove it from Jenkins.  It was provided long ago to allow compatibility between very old and old Jenkins versions.  I do not expect any issues if you remove that plugin from Jenkins 2.263.4
